### ISSUE TITLE
Error: undefined method `ancestors' for nil:NilClass

### ISSUE THREAD

**Issue by littleBro** [jantman/puppet-archlinux-macbookretina#3]
Hi Jason!

I follow your instructions and when I try  "sudo puppet apply --verbose /etc/puppet/manifests/site.pp" I run into this error: "undefined method `ancestors' for nil:NilClass".

Some output from right above in debug mode:

Debug: /Firewall[101 allow mosh]: [validate]
Debug: /Package[xf86-video-nouveau]: Provider pacman does not support features install_options; not managing attribute install_options
Debug: /Package[nouveau-dri]: Provider pacman does not support features install_options; not managing attribute install_options
Debug: /Package[mesa-libgl]: Provider pacman does not support features install_options; not managing attribute install_options
Debug: /Package[lib32-mesa-libgl]: Provider pacman does not support features install_options; not managing attribute install_options
Debug: /Firewall[100 allow ssh]: [validate]
Debug: Puppet::Type::Sysctl::ProviderParsed: file /etc/sysctl.conf does not exist
Debug: Puppet::Type::Sysctl::ProviderParsed: file /etc/sysctl.conf does not exist
Debug: Puppet::Type::Sysctl::ProviderParsed: file /etc/sysctl.conf does not exist

What's the problem? Could you help?

Thanks a lot
Ivan

**Comment by jantman** [comment]
This is now fixed.
