### ISSUE TITLE
Evaluation Error: illegal name

### ISSUE THREAD

**Issue by jmartiuk5** [jantman/puppet-archlinux-macbookretina#6]
Error: Evaluation Error: Illegal name. The given name 'puppet-archlinux-macbookretina::firewall_post' does not conform to the naming rule /^((::)?[a-z_]w*)(::[a-z]\w*)*$/ at /etc/puppetlabs/puppet/manifests/site.pp:20:20 on node archlinux.hsd1.pa.comcast.net

**Comment by jantman** [comment]
I really need to update this (and VERY LIKELY will in the next month or so), but:

1. I haven't used this for a fresh installation in months.
2. This module is written for and tested with puppet 3.6; if I had to guess, that issue is with Puppet 3.8 or 4.

**Comment by jmartiuk5** [comment]
yea thats what it looks like. Thanks for the speedy reply

**Comment by jantman** [comment]
Yeah. Sorry for the old, really-not-usable code. I need to get this largely rewritten, but I've been waiting to take a few vacation days when I can deal with one or both of my computers broken...

**Comment by jmartiuk5** [comment]
Yea this is great great idea that's the only reason i am bummed out. 
I know what its like writing code and having a million other things to attend to and your computers are down. No Fun..... Well i look forward to the next release. This archlinux thing has been a week long project then i had everything working fine and it went into hibernation. 
I tried to wake it up but couldn't so i issued a reboot, when she came back on nothing worked no keyboard no mouse nothing.
I tried everything so now i am installing from scratch again and thought i would try something different.

**Comment by jantman** [comment]
I have NEVER been able to get hibernate to work right under Arch on my macbook, and with Arch installed, I've had issues with OS X hibernate too. That being said, (the people in the Arch community would murder me for saying this) I haven't updated the OS on my macbook in almost a year. My company revoked their work from home policy, and we only have laptops in the office, so I can't risk having a non-working laptop unless I want to take vacation time to fix it...

If you can't use this puppet stuff itself, it (and some of the docs and notes) should at least provide some pointers. I've also found the Arch Wiki to be a great resource.

**Comment by jmartiuk5** [comment]
Yea that's what i am going to have to do no easy way out here. lol listen to this i just followed your guide and dipped between yours and others i just booted into kde for the first time and again no mouse or keyboard this time from the very start but if i pop the live usb back in i get it back. I really cant figure it out.

**Comment by jantman** [comment]
Have you tried using a standard external USB mouse/keyboard? IIRC, I had some issues with the driver for the Mac mouse and keyboard not being installed...

**Comment by jmartiuk5** [comment]
yes they work like a charm when i plug something in.

**Comment by jantman** [comment]
@jmartiuk5 Sorry for the delay in updating this, but this should now be fixed with the major refactor I did of these modules a few months ago.
