### ISSUE TITLE
Nvidia driver on 11,x?

### ISSUE THREAD

**Issue by trusktr** [jantman/puppet-archlinux-macbookretina#7]
Have you tried the `nvidia` driver on 11,x (I'm on 11,5). No luck yet. `nouveau` works fine, but as you might know it's slower. I want to see if I can get the `nvidia` driver working to see if it's more performant.

I've gotten MATE desktop running under `nvidia`, just not GOME, which is what I really want.

**Comment by jantman** [comment]
@trusktr many apologies for not replying for so long, somehow I missed this.

I have tried nvidia, and with the major refactor of this module a few months ago, it's now the default (and works wonderfully).

**Comment by trusktr** [comment]
Nvidia started working for me in Gnome after installing `intel-ucode`, then I updated some things, and it broke again.
